secher<-read.table("secher.txt",header=TRUE)
model<-lm(bwt~bpd,data=secher)
sum.model<-summary(model)
R2<-sum.model$r.squared
f<-sum.model$fstatistic
p.value<-pf(f[1],f[2],f[3],lower.tail=FALSE)
output<-sprintf("R2 = %f and p-value=%f", R2, p.value)
cat(output)
png("bwt_bpd.png")
plot(bwt~bpd,data=secher)
abline(model)
dev.off()
model<-lm(bwt~ad,data=secher)
sum.model<-summary(model)
R2<-sum.model$r.squared
f<-sum.model$fstatistic
p.value<-pf(f[1],f[2],f[3],lower.tail=FALSE)
output<-sprintf("R2 = %f and p-value=%f", R2, p.value)
cat(output)
png("bwt_ad.png")
plot(bwt~ad,data=secher)
abline(model)
dev.off()
names(secher)
model<-lm(bwt~bpd+ad,data=secher)
summary(model)